version: "3"

services:
  fastapi:
    image: fast-api-stations
    ports:
      - "8000:80"

  stationdb:
    image: postgis/postgis
    environment:
      POSTGRES_USER: jkaub
      POSTGRES_PASSWORD: jkaub
      POSTGRES_DB: stations
    volumes:
      - ./db:/var/lib/postgresql/data